[package]
name = "mock-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.17.2"
near-contract-standards = "5.17.2"
borsh = { version = "1.5", features = ["derive"] }
